services:
  frontend:
    build:
      context: .              # 현재 폴더를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile  # 같은 디렉토리에 있는 Dockerfile 사용
    env_file:
      - .env
    container_name: daepa-frontend
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - daepa_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:stable
    container_name: daepa-nginx
    depends_on:
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - daepa_net

networks:
  daepa_net:
    driver: bridge
